export const data = [
    {
        id:1,
        sdate:'2022-09-27 11:00',
        edate:'2022-09-27 11:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'b', //m:남자, f:여자, b:둘 다
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:2,
        sdate:'2022-09-30 11:00',
        edate:'2022-09-27 11:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'m',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:3,
        sdate:'2022-10-01 11:00',
        edate:'2022-09-27 11:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'b',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:4,
        sdate:'2022-10-01 11:00',
        edate:'2022-09-27 11:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'b',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:5,
        sdate:'2022-10-02 11:00',
        edate:'2022-09-27 11:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'b',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:6,
        sdate:'2022-10-03 11:00',
        edate:'2022-09-27 11:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'f',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:7,
        sdate:'2022-10-04 11:00',
        edate:'2022-09-27 11:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'m',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:8,
        sdate:'2022-10-04 11:00',
        edate:'2022-09-27 11:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'b',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:9,
        sdate:'2022-10-06 11:00',
        edate:'2022-09-27 11:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'f',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:10,
        sdate:'2022-10-09 11:00',
        edate:'2022-09-27 11:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'f',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    }
]