export const data = [
    {
        id:1,
        sdate:'2022-11-12 11:00',
        edate:'2022-11-12 13:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'b', //m:남자, f:여자, b:둘 다
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:2,
        sdate:'2022-11-14 12:00',
        edate:'2022-11-14 14:30',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'m',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:3,
        sdate:'2022-11-17 10:00',
        edate:'2022-11-17 12:30',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'b',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:4,
        sdate:'2022-11-18 13:00',
        edate:'2022-11-18 15:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'b',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:5,
        sdate:'2022-11-21 11:00',
        edate:'2022-11-21 14:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'b',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:6,
        sdate:'2022-11-22 11:00',
        edate:'2022-11-22 13:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'f',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:7,
        sdate:'2022-11-23 11:00',
        edate:'2022-11-23 14:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'m',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:8,
        sdate:'2022-11-27 10:00',
        edate:'2022-11-27 12:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'b',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:9,
        sdate:'2022-11-29 15:00',
        edate:'2022-11-29 17:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'f',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    },
    {
        id:10,
        sdate:'2022-11-30 11:00',
        edate:'2022-11-30 14:00',
        mastername:'admin',
        masteremail:'admin@admin.com',
        course:'알펜시아 골프클럽',
        address:'강원 평창군 대관령면 솔봉로 325',
        money:220000,
        membercount:5,
        mchar:'f',
        mcount:3,
        member:['admin@admin.com', 'test@test.com']
    }
]